### ISSUE TITLE
sql errors and more

### ISSUE THREAD

**Issue by lostfile1** [ansiwave/wavecore#2]
im currently using a vps with ubuntu 20.04 and even after i've created the directory's for it it still seems to give me problems
![Screenshot_2022-06-20_15-54-38](https://user-images.githubusercontent.com/41842361/174669955-73043eb4-f21a-4ada-8487-822746483f49.png)

![Screenshot_2022-06-20_15-56-08](https://user-images.githubusercontent.com/41842361/174670265-c05b6515-9f7f-4bfe-8ead-62c88755d85b.png)

and no matter what do with nginx it just takes me to a blank page and before anyone gets any ideas im not going to use that key anymore

**Comment by oakes** [comment]
Looks like you are hitting the server successfully since it's printing out 404s. Is the login key for that board on your computer locally, or did you generate the login key on your server?

**Comment by lostfile1** [comment]
> Looks like you are hitting the server successfully since it's printing out 404s. Is the login key for that board on your computer locally, or did you generate the login key on your server?

I did both. I generated a key on my computer and on the server I mean it's not an authentication issue I was able to log in as admin a couple of times it's just trying to get nginx to display anything or to get the subboards to show up I was having a hard time with And when I tried looking a poster that I recently made up or a test user. I keep getting SQL errors also I had to create the board/db directory in order to get it to at least partly work better

**Comment by lostfile1** [comment]
Another quick question, kind of unrelated but is there any way automate the process of getting users out of limbo like can I make a crontab process That activates after a certain period of time

**Comment by oakes** [comment]
You shouldn't have to create board/db, it will be created when the first post is made. Do you see anything in the board/ansiwave dir?

You can disable limbo by passing `--disable-limbo` when you run wavecore.

**Comment by lostfile1** [comment]
> You shouldn't have to create board/db, it will be created when the first post is made. Do you see anything in the board/ansiwave dir?
> 
> You can disable limbo by passing `--disable-limbo` when you run wavecore.

All right. I'll try poking around with it when I get home

**Comment by oakes** [comment]
I did a quick test in a VM. I went through the steps in the readme. When i opened the board with `ansiwave http://localhost/#board:...` i could see buttons for `create banner` and `create new subboard`. Initially when i tried making a subboard i got a "board does not exist" error. I just fixed that here https://github.com/ansiwave/wavecore/commit/9dbb8cdee359aef0ff7d4960e0b91be931797cb7 After running wavecore with that fix i was able to make a subboard. How far were you able to get in the process? did you ever see the create subboard button?

**Comment by lostfile1** [comment]
So I was able to see the sub board button but unless I created the board/db directory it would not let me And then as I logged in as a normal user, none of the boards that I created showed up The only reason why you don't see it in the image above was partly due to a mix-up on my end I'll give it a try when I get home

**Comment by oakes** [comment]
Yeah you were right, it needed the `board` subdir but that change i just made fixed it. Not sure why the boards didn't show up...make sure you're connecting to the correct URL with `/#board:...` in it.

**Comment by lostfile1** [comment]
> Yeah you were right, it needed the `board` subdir but that change i just made fixed it. Not sure why the boards didn't show up...make sure you're connecting to the correct URL with `/#board:...` in it.

is there any deps other then nim that i need to install

**Comment by lostfile1** [comment]
After some more tinkering around with it it seems to be giving me unhandled URL, errors and file not found I will try and fight with it some more tomorrow maybe it's the distribution I'm using. Maybe I have some dependencies I don't have Tomorrow after work I will send you some more screenshots

**Comment by oakes** [comment]
What's the url you're trying to connect to?

**Comment by lostfile1** [comment]
> What's the url you're trying to connect to?

I don't know but the console would say unhandled  #board/:  .. /db/ for example

**Comment by lostfile1** [comment]
i got it to work i can only use the client to connect to it though if you want to poke around with it the address is http://brokenansi.ddns.net/#board:a9hVjJDW9Sh3rq8K-dWFYEZ2uuqJ_d2qUzSaUmzQPrE
please keep in mind im still working on ansi banners
